recfriio.o: recfriio.cpp setting.hpp error.hpp Recordable.hpp
usbops.o: usbops.cpp usbops.hpp error.hpp AutoCloser.hpp setting.hpp
error.o: error.cpp error.hpp
IoThread.o: IoThread.cpp usbops.hpp error.hpp RingBuf.hpp IoThread.hpp \
 setting.hpp
Recordable.o: Recordable.cpp FriioWhiteWrapper.hpp Recordable.hpp \
 AbstractFriio.hpp setting.hpp error.hpp RingBuf.hpp IoThread.hpp \
 usbops.hpp FriioBlack.hpp
AbstractFriio.o: AbstractFriio.cpp usbops.hpp error.hpp AutoCloser.hpp \
 AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp Recordable.hpp
FriioWhite.o: FriioWhite.cpp usbops.hpp error.hpp FriioWhite.hpp \
 Recordable.hpp AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp
FriioBlack.o: FriioBlack.cpp usbops.hpp error.hpp FriioBlack.hpp \
 Recordable.hpp AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp
FriioWhiteWrapper.o: FriioWhiteWrapper.cpp usbops.hpp error.hpp \
 FriioWhiteWrapper.hpp Recordable.hpp AbstractFriio.hpp setting.hpp \
 RingBuf.hpp IoThread.hpp FriioExpress.hpp FriioWhite.hpp
FriioExpress.o: FriioExpress.cpp usbops.hpp error.hpp FriioExpress.hpp \
 Recordable.hpp AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp
B25Decoder.o: B25Decoder.cpp ../arib25/arib_std_b25.h \
 ../arib25/portable.h ../arib25/b_cas_card.h ../arib25/b_cas_card.h \
 B25Decoder.hpp error.hpp
Hdus.o: Hdus.cpp usbops.hpp error.hpp Hdus.hpp Recordable.hpp \
 AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp decrypt.c
Hdp.o: Hdp.cpp usbops.hpp error.hpp Hdp.hpp Recordable.hpp \
 AbstractFriio.hpp setting.hpp RingBuf.hpp IoThread.hpp decrypt.c
Udp.o: Udp.cpp Udp.hpp
tssplitter_lite.o: tssplitter_lite.cpp ../arib25/arib_std_b25.h \
 ../arib25/portable.h ../arib25/b_cas_card.h ../arib25/b_cas_card.h \
 tssplitter_lite.hpp
